export const CHANGE_SEARCH_FIELD = '_CHANGE_SEARCH_FIELD_';

export const REQUEST_ROBOTS_PENDING = '_REQUEST_ROBOTS_PENDING_';
export const REQUEST_ROBOTS_SUCCESS = '_REQUEST_ROBOTS_SUCCESS_';
export const REQUEST_ROBOTS_FAILED = '_REQUEST_ROBOTS_FAILED_';